// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: characters.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createCharacter = `-- name: CreateCharacter :one
INSERT INTO characters (
    id, 
    name, 
    description, 
    alignment, 
    total_level, 
    experience, 
    armor_class, 
    hit_points, 
    current_hit_points, 
    strength, 
    dexterity, 
    constitution, 
    intelligence, 
    wisdom, 
    charisma, 
    traits, 
    flaws
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
) RETURNING id, name, description, alignment, total_level, experience, armor_class, hit_points, current_hit_points, speed, proficiency_bonus, strength, dexterity, constitution, intelligence, wisdom, charisma, traits, flaws, race_id, background_id
`

type CreateCharacterParams struct {
	ID               uuid.UUID
	Name             string
	Description      sql.NullString
	Alignment        NullAlignment
	TotalLevel       int32
	Experience       int32
	ArmorClass       int32
	HitPoints        int32
	CurrentHitPoints int32
	Strength         int32
	Dexterity        int32
	Constitution     int32
	Intelligence     int32
	Wisdom           int32
	Charisma         int32
	Traits           []string
	Flaws            []string
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, createCharacter,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Alignment,
		arg.TotalLevel,
		arg.Experience,
		arg.ArmorClass,
		arg.HitPoints,
		arg.CurrentHitPoints,
		arg.Strength,
		arg.Dexterity,
		arg.Constitution,
		arg.Intelligence,
		arg.Wisdom,
		arg.Charisma,
		pq.Array(arg.Traits),
		pq.Array(arg.Flaws),
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Alignment,
		&i.TotalLevel,
		&i.Experience,
		&i.ArmorClass,
		&i.HitPoints,
		&i.CurrentHitPoints,
		&i.Speed,
		&i.ProficiencyBonus,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		pq.Array(&i.Traits),
		pq.Array(&i.Flaws),
		&i.RaceID,
		&i.BackgroundID,
	)
	return i, err
}

const deleteCharacter = `-- name: DeleteCharacter :exec
DELETE FROM characters WHERE id = $1
`

func (q *Queries) DeleteCharacter(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCharacter, id)
	return err
}

const getCharacter = `-- name: GetCharacter :one
SELECT id, name, description, alignment, total_level, experience, armor_class, hit_points, current_hit_points, speed, proficiency_bonus, strength, dexterity, constitution, intelligence, wisdom, charisma, traits, flaws, race_id, background_id FROM characters
WHERE id = $1
`

func (q *Queries) GetCharacter(ctx context.Context, id uuid.UUID) (Character, error) {
	row := q.db.QueryRowContext(ctx, getCharacter, id)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Alignment,
		&i.TotalLevel,
		&i.Experience,
		&i.ArmorClass,
		&i.HitPoints,
		&i.CurrentHitPoints,
		&i.Speed,
		&i.ProficiencyBonus,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		pq.Array(&i.Traits),
		pq.Array(&i.Flaws),
		&i.RaceID,
		&i.BackgroundID,
	)
	return i, err
}

const listCharacters = `-- name: ListCharacters :many
SELECT id, name, description, alignment, total_level, experience, armor_class, hit_points, current_hit_points, speed, proficiency_bonus, strength, dexterity, constitution, intelligence, wisdom, charisma, traits, flaws, race_id, background_id FROM characters 
ORDER BY name
`

func (q *Queries) ListCharacters(ctx context.Context) ([]Character, error) {
	rows, err := q.db.QueryContext(ctx, listCharacters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Alignment,
			&i.TotalLevel,
			&i.Experience,
			&i.ArmorClass,
			&i.HitPoints,
			&i.CurrentHitPoints,
			&i.Speed,
			&i.ProficiencyBonus,
			&i.Strength,
			&i.Dexterity,
			&i.Constitution,
			&i.Intelligence,
			&i.Wisdom,
			&i.Charisma,
			pq.Array(&i.Traits),
			pq.Array(&i.Flaws),
			&i.RaceID,
			&i.BackgroundID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
