// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: characters.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCharacter = `-- name: CreateCharacter :one
INSERT INTO characters (
    id, name, description, level, experience, 
    armor_class, hit_points, strength, dexterity, 
    constitution, intelligence, wisdom, charisma
) VALUES (
    $1, $2, $3, $4, $5, 
    $6, $7, $8, $9, 
    $10, $11, $12, $13
) RETURNING id, name, description, level, experience, armor_class, hit_points, strength, dexterity, constitution, intelligence, wisdom, charisma
`

type CreateCharacterParams struct {
	ID           uuid.UUID
	Name         string
	Description  sql.NullString
	Level        int32
	Experience   int32
	ArmorClass   int32
	HitPoints    int32
	Strength     int32
	Dexterity    int32
	Constitution int32
	Intelligence int32
	Wisdom       int32
	Charisma     int32
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, createCharacter,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Level,
		arg.Experience,
		arg.ArmorClass,
		arg.HitPoints,
		arg.Strength,
		arg.Dexterity,
		arg.Constitution,
		arg.Intelligence,
		arg.Wisdom,
		arg.Charisma,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Level,
		&i.Experience,
		&i.ArmorClass,
		&i.HitPoints,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
	)
	return i, err
}

const deleteCharacter = `-- name: DeleteCharacter :exec
DELETE FROM characters WHERE id = $1
`

func (q *Queries) DeleteCharacter(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCharacter, id)
	return err
}

const getCharacter = `-- name: GetCharacter :one
SELECT 
    c.id, c.name, c.description, c.level, c.experience, c.armor_class, c.hit_points, c.strength, c.dexterity, c.constitution, c.intelligence, c.wisdom, c.charisma,
    cl.name AS class_name,
    cc.class_level
FROM characters c
JOIN character_classes cc ON c.id = cc.character_id 
JOIN classes cl ON cc.class_id = cl.id
`

type GetCharacterRow struct {
	ID           uuid.UUID
	Name         string
	Description  sql.NullString
	Level        int32
	Experience   int32
	ArmorClass   int32
	HitPoints    int32
	Strength     int32
	Dexterity    int32
	Constitution int32
	Intelligence int32
	Wisdom       int32
	Charisma     int32
	ClassName    string
	ClassLevel   sql.NullInt32
}

func (q *Queries) GetCharacter(ctx context.Context) (GetCharacterRow, error) {
	row := q.db.QueryRowContext(ctx, getCharacter)
	var i GetCharacterRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Level,
		&i.Experience,
		&i.ArmorClass,
		&i.HitPoints,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.ClassName,
		&i.ClassLevel,
	)
	return i, err
}

const listCharacters = `-- name: ListCharacters :many
SELECT id, name, description, level, experience, armor_class, hit_points, strength, dexterity, constitution, intelligence, wisdom, charisma FROM characters 
ORDER BY name
`

func (q *Queries) ListCharacters(ctx context.Context) ([]Character, error) {
	rows, err := q.db.QueryContext(ctx, listCharacters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Level,
			&i.Experience,
			&i.ArmorClass,
			&i.HitPoints,
			&i.Strength,
			&i.Dexterity,
			&i.Constitution,
			&i.Intelligence,
			&i.Wisdom,
			&i.Charisma,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCharacterStats = `-- name: UpdateCharacterStats :exec
UPDATE characters
SET 
    level = $2,
    experience = $3,
    hit_points = $4,
    strength = $5,
    dexterity = $6,
    constitution = $7,
    intelligence = $8,
    wisdom = $9,
    charisma = $10
WHERE id = $1
`

type UpdateCharacterStatsParams struct {
	ID           uuid.UUID
	Level        int32
	Experience   int32
	HitPoints    int32
	Strength     int32
	Dexterity    int32
	Constitution int32
	Intelligence int32
	Wisdom       int32
	Charisma     int32
}

func (q *Queries) UpdateCharacterStats(ctx context.Context, arg UpdateCharacterStatsParams) error {
	_, err := q.db.ExecContext(ctx, updateCharacterStats,
		arg.ID,
		arg.Level,
		arg.Experience,
		arg.HitPoints,
		arg.Strength,
		arg.Dexterity,
		arg.Constitution,
		arg.Intelligence,
		arg.Wisdom,
		arg.Charisma,
	)
	return err
}
