// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: classes.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addClassToCharacter = `-- name: AddClassToCharacter :one
INSERT INTO character_classes (character_id, class_id, class_level) 
VALUES ($1, $2, $3)
RETURNING character_id, class_id, class_level
`

type AddClassToCharacterParams struct {
	CharacterID uuid.UUID
	ClassID     int32
	ClassLevel  sql.NullInt32
}

func (q *Queries) AddClassToCharacter(ctx context.Context, arg AddClassToCharacterParams) (CharacterClass, error) {
	row := q.db.QueryRowContext(ctx, addClassToCharacter, arg.CharacterID, arg.ClassID, arg.ClassLevel)
	var i CharacterClass
	err := row.Scan(&i.CharacterID, &i.ClassID, &i.ClassLevel)
	return i, err
}

const getClassesByCharacterID = `-- name: GetClassesByCharacterID :many
SELECT c.id, c.name, cc.class_level
FROM classes c
JOIN character_classes cc ON c.id = cc.class_id
WHERE cc.character_id = $1
`

type GetClassesByCharacterIDRow struct {
	ID         int32
	Name       string
	ClassLevel sql.NullInt32
}

func (q *Queries) GetClassesByCharacterID(ctx context.Context, characterID uuid.UUID) ([]GetClassesByCharacterIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getClassesByCharacterID, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetClassesByCharacterIDRow
	for rows.Next() {
		var i GetClassesByCharacterIDRow
		if err := rows.Scan(&i.ID, &i.Name, &i.ClassLevel); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllClasses = `-- name: ListAllClasses :many
SELECT id, name FROM classes ORDER BY name
`

func (q *Queries) ListAllClasses(ctx context.Context) ([]Class, error) {
	rows, err := q.db.QueryContext(ctx, listAllClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Class
	for rows.Next() {
		var i Class
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
