// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: flaws.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createFlaw = `-- name: CreateFlaw :one
INSERT INTO flaws (id, character_id, description) 
VALUES ($1, $2, $3)
RETURNING id, description, character_id
`

type CreateFlawParams struct {
	ID          uuid.UUID
	CharacterID uuid.UUID
	Description string
}

func (q *Queries) CreateFlaw(ctx context.Context, arg CreateFlawParams) (Flaw, error) {
	row := q.db.QueryRowContext(ctx, createFlaw, arg.ID, arg.CharacterID, arg.Description)
	var i Flaw
	err := row.Scan(&i.ID, &i.Description, &i.CharacterID)
	return i, err
}

const deleteFlaw = `-- name: DeleteFlaw :exec
DELETE FROM flaws 
WHERE id = $1
`

func (q *Queries) DeleteFlaw(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFlaw, id)
	return err
}

const getFlawsByCharacterID = `-- name: GetFlawsByCharacterID :many
SELECT id, description, character_id FROM flaws 
WHERE character_id = $1
ORDER BY description
`

func (q *Queries) GetFlawsByCharacterID(ctx context.Context, characterID uuid.UUID) ([]Flaw, error) {
	rows, err := q.db.QueryContext(ctx, getFlawsByCharacterID, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flaw
	for rows.Next() {
		var i Flaw
		if err := rows.Scan(&i.ID, &i.Description, &i.CharacterID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
