// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Character struct {
	ID           uuid.UUID
	Name         string
	Description  sql.NullString
	Level        int32
	Experience   int32
	ArmorClass   int32
	HitPoints    int32
	Strength     int32
	Dexterity    int32
	Constitution int32
	Intelligence int32
	Wisdom       int32
	Charisma     int32
}

type CharacterClass struct {
	CharacterID uuid.UUID
	ClassID     int32
	ClassLevel  sql.NullInt32
}

type Class struct {
	ID   int32
	Name string
}

type Flaw struct {
	ID          uuid.UUID
	Description string
	CharacterID uuid.UUID
}

type Trait struct {
	ID          uuid.UUID
	Description string
	CharacterID uuid.UUID
}
