// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddClassToCharacter(ctx context.Context, arg AddClassToCharacterParams) (CharacterClass, error)
	CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error)
	DeleteCharacter(ctx context.Context, id uuid.UUID) error
	GetCharacter(ctx context.Context, id uuid.UUID) (Character, error)
	GetCharacterClasses(ctx context.Context, characterID uuid.UUID) ([]GetCharacterClassesRow, error)
	ListAllClasses(ctx context.Context) ([]Class, error)
	ListCharacters(ctx context.Context) ([]Character, error)
}

var _ Querier = (*Queries)(nil)
