// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddClassToCharacter(ctx context.Context, arg AddClassToCharacterParams) (CharacterClass, error)
	CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error)
	CreateFlaw(ctx context.Context, arg CreateFlawParams) (Flaw, error)
	CreateTrait(ctx context.Context, arg CreateTraitParams) (Trait, error)
	DeleteCharacter(ctx context.Context, id uuid.UUID) error
	DeleteFlaw(ctx context.Context, id uuid.UUID) error
	DeleteTrait(ctx context.Context, id uuid.UUID) error
	GetCharacter(ctx context.Context) (GetCharacterRow, error)
	GetClassesByCharacterID(ctx context.Context, characterID uuid.UUID) ([]GetClassesByCharacterIDRow, error)
	GetFlawsByCharacterID(ctx context.Context, characterID uuid.UUID) ([]Flaw, error)
	GetTraitsByCharacterID(ctx context.Context, characterID uuid.UUID) ([]Trait, error)
	ListAllClasses(ctx context.Context) ([]Class, error)
	ListCharacters(ctx context.Context) ([]Character, error)
	UpdateCharacterStats(ctx context.Context, arg UpdateCharacterStatsParams) error
}

var _ Querier = (*Queries)(nil)
