// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: traits.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createTrait = `-- name: CreateTrait :one
INSERT INTO traits (id, character_id, description) 
VALUES ($1, $2, $3)
RETURNING id, description, character_id
`

type CreateTraitParams struct {
	ID          uuid.UUID
	CharacterID uuid.UUID
	Description string
}

func (q *Queries) CreateTrait(ctx context.Context, arg CreateTraitParams) (Trait, error) {
	row := q.db.QueryRowContext(ctx, createTrait, arg.ID, arg.CharacterID, arg.Description)
	var i Trait
	err := row.Scan(&i.ID, &i.Description, &i.CharacterID)
	return i, err
}

const deleteTrait = `-- name: DeleteTrait :exec
DELETE FROM traits 
WHERE id = $1
`

func (q *Queries) DeleteTrait(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTrait, id)
	return err
}

const getTraitsByCharacterID = `-- name: GetTraitsByCharacterID :many
SELECT id, description, character_id FROM traits 
WHERE character_id = $1
ORDER BY description
`

func (q *Queries) GetTraitsByCharacterID(ctx context.Context, characterID uuid.UUID) ([]Trait, error) {
	rows, err := q.db.QueryContext(ctx, getTraitsByCharacterID, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trait
	for rows.Next() {
		var i Trait
		if err := rows.Scan(&i.ID, &i.Description, &i.CharacterID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
