CREATE TYPE action_cost_type AS ENUM (
    'action',
    'bonus_action',
    'reaction',
    'movement',
    'none'
);

CREATE TYPE attack_type AS ENUM (
    'melee_weapon',
    'ranged_weapon',
    'melee_spell',
    'ranged_spell',
    'none'
);

CREATE TYPE alignment AS ENUM (
    'lawful_good',
    'neutral_good',
    'chaotic_good',
    'lawful_neutral',
    'true_neutral',
    'chaotic_neutral',
    'lawful_evil',
    'neutral_evil',
    'chaotic_evil'
);

CREATE TYPE damage_type AS ENUM (
    'bludgeoning',
    'piercing',
    'slashing',
    'acid',
    'cold',
    'fire',
    'force',
    'lightning',
    'necrotic',
    'poison',
    'psychic',
    'radiant',
    'thunder'
);

CREATE TABLE races (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL
);

CREATE TABLE backgrounds (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL
);

CREATE TABLE spell_slots (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level INT NOT NULL,
    quantity INT NOT NULL
);

CREATE TABLE classes (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL
);

CREATE TABLE subclasses (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    unlocked_level INT NOT NULL,
    class_id INT REFERENCES classes(id)
);

CREATE TABLE skills (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL
);

CREATE TABLE damage_formula (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dice_count INT,
    dice_value INT,
    damage_type damage_type
);

CREATE TABLE characters (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    alignment alignment,
    total_level INT NOT NULL DEFAULT 1,
    experience INT NOT NULL DEFAULT 0,
    armor_class INT NOT NULL DEFAULT 10,
    hit_points INT NOT NULL,
    current_hit_points INT NOT NULL,
    speed INT,
    proficiency_bonus INT,
    strength INT NOT NULL,
    dexterity INT NOT NULL,
    constitution INT NOT NULL,
    intelligence INT NOT NULL,
    wisdom INT NOT NULL,
    charisma INT NOT NULL,
    traits TEXT[], 
    flaws TEXT[],

    race_id INT REFERENCES races(id),
    background_id INT REFERENCES backgrounds(id)
);

CREATE TABLE character_classes (
    character_id UUID NOT NULL,
    class_id INT NOT NULL,
    class_level INT,
    CONSTRAINT pk_char_classes PRIMARY KEY (character_id, class_id),
    CONSTRAINT fk_char_classes_character FOREIGN KEY (character_id) REFERENCES characters(id) ON DELETE CASCADE,
    CONSTRAINT fk_char_classes_class FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE
);

CREATE TABLE character_skills (
    character_id UUID NOT NULL,
    skill_id INT NOT NULL,
    CONSTRAINT pk_char_skills PRIMARY KEY (character_id, skill_id),
    CONSTRAINT fk_char_skills_character FOREIGN KEY (character_id) REFERENCES characters(id) ON DELETE CASCADE,
    CONSTRAINT fk_char_skills_skill FOREIGN KEY (skill_id) REFERENCES skills(id) ON DELETE CASCADE
);

CREATE TABLE character_spell_slots (
    character_id UUID NOT NULL,
    spell_slot_id INT NOT NULL,
    CONSTRAINT pk_char_spell_slots PRIMARY KEY (character_id, spell_slot_id),
    CONSTRAINT fk_char_spell_slots_character FOREIGN KEY (character_id) REFERENCES characters(id) ON DELETE CASCADE,
    CONSTRAINT fk_char_spell_slots_spell_slot FOREIGN KEY (spell_slot_id) REFERENCES spell_slots(id) ON DELETE CASCADE
);

CREATE TABLE action_definitions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,

    cost_type action_cost_type NOT NULL,
    attack_type attack_type NOT NULL, 

    range_normal INT,
    range_long INT,

    damage_formula_id INT REFERENCES damage_formula(id) 
);

CREATE TABLE items (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    cost INT NOT NULL DEFAULT 0,
    weight INT NOT NULL,

    action_definition_id INT REFERENCES action_definitions(id)
);

CREATE TABLE feats (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description TEXT, 
    action_definition_id INT REFERENCES action_definitions(id)
);

CREATE TABLE spells (
    id UUID PRIMARY KEY,
    name VARCHAR(255),
    school VARCHAR(255),
    spell_cost INT, 
    spell_level INT,

    action_definition_id INT REFERENCES action_definitions(id)
);

CREATE TABLE character_inventory (
    character_id UUID NOT NULL,
    item_id UUID NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    is_equipped BOOLEAN NOT NULL DEFAULT FALSE, 
    
    CONSTRAINT pk_character_inventory PRIMARY KEY (character_id, item_id),
    CONSTRAINT fk_inventory_character FOREIGN KEY (character_id) REFERENCES characters(id) ON DELETE CASCADE,
    CONSTRAINT fk_inventory_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
);

CREATE TABLE character_spells (
    character_id UUID NOT NULL,
    spell_id UUID NOT NULL,
    is_prepared BOOLEAN NOT NULL DEFAULT FALSE, 
    
    CONSTRAINT pk_character_spells PRIMARY KEY (character_id, spell_id),
    CONSTRAINT fk_spells_character FOREIGN KEY (character_id) REFERENCES characters(id) ON DELETE CASCADE,
    CONSTRAINT fk_spells_spell FOREIGN KEY (spell_id) REFERENCES spells(id) ON DELETE CASCADE
);

CREATE TABLE character_feats (
    character_id UUID NOT NULL,
    feat_id INT NOT NULL, 
    
    CONSTRAINT pk_character_feats PRIMARY KEY (character_id, feat_id),
    CONSTRAINT fk_feats_character FOREIGN KEY (character_id) REFERENCES characters(id) ON DELETE CASCADE,
    CONSTRAINT fk_feat_feats FOREIGN KEY (feat_id) REFERENCES feats(id) ON DELETE CASCADE -- Correção: nome da tabela feat -> feats
);