CREATE TABLE characters (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    level INT NOT NULL DEFAULT 1,
    experience INT NOT NULL DEFAULT 0,
    armor_class INT NOT NULL DEFAULT 10,
    hit_points INT NOT NULL,
    strength INT NOT NULL,
    dexterity INT NOT NULL,
    constitution INT NOT NULL,
    intelligence INT NOT NULL,
    wisdom INT NOT NULL,
    charisma INT NOT NULL
);

CREATE TABLE traits (
    id UUID PRIMARY KEY,
    description TEXT NOT NULL,
    character_id UUID NOT NULL,
    CONSTRAINT fk_traits_character FOREIGN KEY (character_id) REFERENCES characters(id) ON DELETE CASCADE
);

CREATE TABLE flaws (
    id UUID PRIMARY KEY,
    description TEXT NOT NULL,
    character_id UUID NOT NULL,
    CONSTRAINT fk_flaws_character FOREIGN KEY (character_id) REFERENCES characters(id) ON DELETE CASCADE
);

CREATE TABLE classes (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE character_classes (
    character_id UUID NOT NULL,
    class_id INT NOT NULL,
    class_level INT,
    CONSTRAINT pk_char_classes PRIMARY KEY (character_id, class_id),
    CONSTRAINT fk_char_classes_character FOREIGN KEY (character_id) REFERENCES characters(id) ON DELETE CASCADE,
    CONSTRAINT fk_char_classes_class FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE
);